### ISSUE TITLE
Accessing custom repository methods within a readWrite transaction

### ISSUE THREAD

**Issue by sebarthel89** [googleapis/java-spanner#1340]
**Is your feature request related to a problem? Please describe.**
Transaction management is essential for creating reliable applications. Spanner allows us to create an interface and add custom methods for example by creating new method following naming conventions. 

For example:

`deleteByColumn(String columnValue)`

Based on the name, Spanner data will execute a delete query and delete every row where column == columnValue.

For transaction management, we prefer programmatic transaction management calling the method on the SpannerRepository

`performReadWriteTransaction`

Unfortunately, this method returns 

`SpannerRepository<T, ID>` that does not provide us custom methods, that we added to our custom repository interface. Therefore, the usage of custom-added methods on a repository is limited.

**Describe the solution you'd like**
Adapt the spanner data implementation and update performReadWriteTransaction to get a function with a parameter type of the custom subclass. This could be done with generics, but the actual implementation of the parent class and related parts need to be adapted. Also, this is not a breaking change because customers of spring data anyhow can for now only use SpannerRepository methods. The new way would require that the interface extends SpannerRepository, therefore, it should not break any build.

In short, the combination of custom repository and programmatic transaction handling should work without any limitations. It's a key selling point of Spanner and part of every application.

**Describe alternatives you've considered**
For now, we try to use methods of the SpannerRepository base class and avoid many custom methods in case if we need to group multiple executions within a single transaction. If this is really needed, we will try to fall back to SpannerOperations and execute queries manually using the SpannerTemplate.

Thanks in advance!

**Comment by olavloite** [comment]
@sebarthel89 If I understand your issue correctly, this issue is related to the Spanner Spring Data implementation that is maintained in [this repository](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/tree/main/spring-cloud-gcp-data-spanner), and then specifically this method: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/ebef98adf02fc152ac59dc2abc112b8442237e8e/spring-cloud-gcp-data-spanner/src/main/java/com/google/cloud/spring/data/spanner/repository/SpannerRepository.java#L52

If that is correct, it would be better if you re-filed this issue in that repository, as it is maintained by a different team and it is not something that we can change in the client library. Please also let me know if I misunderstood your issue.

**Comment by sebarthel89** [comment]
ohh sorry, my bad! I will reopen the issue in the other repository. my bad

**Comment by sebarthel89** [comment]
created: https://github.com/GoogleCloudPlatform/spring-cloud-gcp/issues/568
