### ISSUE TITLE
Getting "JdbcAbortedDueToConcurrentModificationException" while executing two transactions at a time.

### ISSUE THREAD

**Issue by nayanbijagare** [googleapis/java-spanner#1829]
I am using readwrite transaction with hibernate.  When I am trying to hit rest API twice at a same time for read and updating the same column data, I am getting below issue.

com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcAbortedDueToConcurrentModificationException: The transaction was aborted and could not be retried due to a concurrent modification

ABORTED: Deadlock with higher priority transaction. retry_delay { nanos: }

Could you please suggest how to handle this in the Hibernate.
Sample code - 

```
@Transactional(propagation = Propagation.REQUIRES_NEW)
	@Retryable
	public void getAndUpdateSequence(int empId) {
		int lastSequence = employeeRepository.getLastSequenceByEmpId(empId);
		
		int updatedSeq = lastSequence + 1;
		employeeRepository.updateLastSequence(updatedSeq, empId);
}
```

**Comment by olavloite** [comment]
The behavior that you are seeing is intentional and means that the JDBC driver tried to retry the transaction internally, but during the retry observed different data than during the initial attempt. It then throws the exception that you are seeing to prevent the application from making decisions based on stale data.

There are a couple of options that you could use to fix this:

1. Using Spring `@Retryable` should work. However; it requires that you have set up Spring retry correctly (this for example also requires `@EnableRetry` to be added to your application configuration. See https://www.baeldung.com/spring-retry for a full example. You should also consider adding `JdbcAbortedDueToConcurrentModificationException.class` as the exception that you want to retry to the `@Retryable` annotation to ensure only that exception is retried, and not any other exception. Also remember that `@Retryable` will only retry the method 3 times by default before giving up / trying the recover method (that is not defined in your example).
2. You can work around this by using a manual retry loop instead of the `@Retryable` annotation like this:

```java
// Call this method from your application
public void getAndUpdateSequenceRetryable(int empId) {
  final int maxRetries = 1000;
  for (int i=0; i < maxRetries; i++) {
    try {
      getAndUpdateSequence(int empId);
      return;
    } catch (JdbcAbortedDueToConcurrentModificationException e) {
      // ignore
    }
  }
  throw new RuntimeException("Max retries exceeded");
}

@Transactional(propagation = Propagation.REQUIRES_NEW)
void getAndUpdateSequence(int empId) {
  int lastSequence = employeeRepository.getLastSequenceByEmpId(empId);
		
  int updatedSeq = lastSequence + 1;
  employeeRepository.updateLastSequence(updatedSeq, empId);
}
```
