### ISSUE TITLE
Maven version is not automatically updated in README

### ISSUE THREAD

**Issue by olavloite** [googleapis/java-spanner#1839]
The Maven version is not automatically updated in the README file: https://github.com/googleapis/java-spanner/blob/3c55eb336e77ee1ddfb6c055722697f81419578c/README.md?plain=1#L44

* The most recent version of the library is 6.23.2
* The README says to use 6.21.2

**Comment by rajatbhatta** [comment]
[This](https://github.com/googleapis/java-spanner/pull/1788) PR was automatically generated (on March 28, 2022) by @renovate-bot for changing the google-cloud-spanner version in the README file. But the PR was merged late into main (on April 22, 2022) after version upgrades in the same PR, which is why when you logged this issue (on April 20, 2022), it showed an older version.

**Comment by rajatbhatta** [comment]
@olavloite: Feel free to close this issue, if this looks good to you! Thanks!
