### ISSUE TITLE
Fallback to check grpc error message when ResourceType nil

### ISSUE THREAD

**Issue by rahul2393** [googleapis/java-spanner#2208]
[C++](https://github.com/googleapis/google-cloud-cpp/blob/21bad1fc7c22d472f8ba8d9194dfe54342c29e2b/google/cloud/spanner/internal/status_utils.cc#L28-L50), Go and [NodeJS](https://github.com/googleapis/nodejs-spanner/blob/main/src/session-pool.ts#L226) client libraries fallback to check error message for detecting "Session Not Found" errors this ticket is to follow the same strategy in JAVA client.

**Comment by arpan14** [comment]
Java library extracts this information the same way as what the C++ library does. Presently there is a dependency on `resourceType` as well.
https://github.com/googleapis/java-spanner/blob/main/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SpannerExceptionFactory.java#L211

I'm investigating what additional changes are needed when `resourceType` is null.

**Comment by arpan14** [comment]
Post looking more into the Java code, I think we should check with the backend on how we can make sure that the `resourceType` field is never null. Reasons why I think, adding a handling in clients is not the best solution,
1. The proposed solution for looking into error message is hacky and does not look like an authoritative way to identify the session not found errors. There is no guarantee that such error messages cannot be null or cannot change in future. Hence, I'd like to avoid this approach.
2. `Session` is just one of the error types. From code I see we have other resource types like `Instance` and `Database` which can suffer from the same error systems as sessions when the resource type is null. Hence, instead of adding hacks in all clients, we should check with backend on how resource type can be made non-null in case of `NOT_FOUND` error codes.

@olavloite @rahul2393 Let me know you thoughts here and if there is any additional background that I am unaware of.

**Comment by olavloite** [comment]
I agree with @arpan14 that we should not rely on extracting the type of error from the error message whenever possible. We also have other errors that rely on the `ResourceInfo` that is sent, and it could be that customers who implement their own clients also do. I would say that the existence of `ResourceInfo` in these errors is part of the API contract, so it's not something that we can freely remove.

We should ensure that we run our integration tests nightly against cloud-devel/cloud-staging to ensure that we catch this kind of thing early (which I believe we now do?).

**Comment by arpan14** [comment]
@olavloite Thanks, I chatted more with @rahul2393 and I think we are good to close this issue without making any additional code changes.
1. We received `resourceType`  as null due to an outage. In general, there is an established contract that this would be non-null. Hence, our existing code is sufficient.
2. We have taken the additional measure to have tests in cloud-devel/cloud-staging and this will ensure that the similar issues don't repeat in production.
