### ISSUE TITLE
Add support for enum key

### ISSUE THREAD

**Issue by toyopilgrim** [googleapis/java-spanner#2527]
**Is your feature request related to a problem? Please describe.**

Currently, the class `Key` doesn't accept enum value. 

`Key.of(FooEnum.HOGE)` will cause the following error

```
java.lang.IllegalArgumentException: Unsupported type [jp.myapp.FooEnum] for argument: HOGE
at com.google.cloud.spanner.Key$Builder.appendObject(Key.java:198)
at com.google.cloud.spanner.Key.of(Key.java:84)
```

**Describe the solution you'd like**
Accept enum value as well as other types.

**Describe alternatives you've considered**

`Key.of(FooEnum.HOGE.name)` is the current workaround when a part of the keys is enum.  
It'd be more convenient if user doesn’t t need to this as Spanner table entity accepts enum value.

**Comment by olavloite** [comment]
@toyopilgrim Thanks for your feature request. One of the reasons that enums are not supported as key values, is that it would be slightly ambiguous. I noticed that you assume that it would translate to a string and use the name of the enum.

There could however be other reasonable choices as well, such as:
1. Use the `name()` as your suggestion is.
2. Use the `toString()` value.
3. Use the `ordinal()` of the enum, which would translate to an `INT64` column.

Another reason that this automatic conversion is not supported is that it would prohibit us from mapping Java enums to any possible future data type that could be more similar to enums, as that would be introducing a breaking change. I'm therefore inclined to say that it's better if you continue to explicitly pass in the name of the enum, instead of the library automatically converting enums to strings.

**Comment by toyopilgrim** [comment]
@olavloite 
Thx for your reply. I see. As this is low level API, to avoid converting enum makes sense. 

>Spanner table entity accepts enum value.

I meant that this automatically converts enums to its names. 
However, it turned out that this behavior looks like a upper layer thing. : spring cloud gcp 

`import com.google.cloud.spring.data.spanner.core.mapping.Column`

**Comment by olavloite** [comment]
@toyopilgrim Based on the above information I'm closing this feature request. Please feel free to reopen if you feel that there is something that we should change in this library.
