### ISSUE TITLE
Instrument Spanner client (session pool) with OpenCensus metrics

### ISSUE THREAD

**Issue by mayurkale22** [googleapis/java-spanner#53]
**Is your feature request related to a problem? Please describe.**
Customers run into the Cloud Spanner session pool tuning issues for their specific workload on a regular basis. Improved visibility into the state of the session pool (or client side metrics) maintained by each client can provide actionable insight and help users take informed decisions.

This will also help customers in identifying a session leaks.

**Describe the solution you'd like**
Instrument Spanner client (session pool) with [OpenCensus](https://opencensus.io/stats/) metrics. we need to capture things including - number of max sessions, number of sessions in use, leaked sessions, count of active spanner requests, count of released and acquired sessions.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

===================================================================
Edit1: Agreed list of useful metrics:

All the metrics will be prefixed by “cloud.google.com/java/spanner/”.
| Metric | Description | Type | Labels |
| ------------- | ------------- | ------------- | ------------- |
| max_in_use_sessions | The maximum number of sessions in use during the last 10 minute interval | Gauge  | database, instance_id, library_version |
| max_allowed_sessions  | The maximum number of sessions allowed. Configurable by the user | Gauge  | database, instance_id, library_version |
| ~in_use_sessions~  | ~The number of sessions currently in use~  | ~Gauge~  | ~database, instance_id, library_version~ |
| get_session_timeouts  | The number of get sessions timeouts due to pool exhaustion  | Counter  | database, instance_id, library_version |
| num_acquired_sessions  | The number of sessions acquired from the session pool | Counter  | database, instance_id, library_version |
| num_released_sessions  | The number of sessions released by the user and pool maintainer  | Counter  | database, instance_id, library_version |
| num_sessions_in_pool | The number of sessions in the pool.  | Gauge  | database, instance_id, library_version, Type |

* Type : num_in_use_sessions | num_sessions_being_prepared | num_read_sessions | num_write_prepared_sessions

/cc @skuruppu

**Comment by olavloite** [comment]
I think that we should consider adding metrics for monitoring whether the user has chosen a good value for `SessionPoolOptions.writeSessionsFraction`. This could include:
* The number of write sessions that are present in the pool by default (i.e. `minSessions * writeSessionsFraction`).
* The current number of write sessions in use.
* The max number of concurrent write-prepared sessions needed during the last maintenance interval (the last 10 minutes). If this number often exceeds the default number of write-prepared sessions in the pool, it is an indication that the user should increase the number of write-prepared sessions by increasing `writeSessionsFraction` and/or `minSessions`.

**Comment by olavloite** [comment]
Another interesting metric could be to measure the duration that a session has been checked out of the pool. Currently, a user will only be informed about a session leak when closing the session pool, or when the pool has been exhausted. A metric that monitors this duration for all sessions in the pool will show one or more sessions that have an ever increasing checked out duration in case of a session leak.

**Comment by mayurkale22** [comment]
> Another interesting metric could be to measure the duration that a session has been checked out of the pool.

Could you please point out the code from where I can fetch this number.

I was thinking to add a counter to measure the count of pool (resource) exhausted or no session available in the pool, to indicate session leaks. WDYT? If this is not the right place, It would be nice if you can point me to the code to get the session leak data.

https://github.com/googleapis/java-spanner/blob/f3ca198f4ba37ed81fa71b4db4866cbfb27c5bd5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L1430-L1440

**Comment by mayurkale22** [comment]
@skuruppu What do you think about https://github.com/googleapis/java-spanner/issues/53#issuecomment-582027067?

**Comment by olavloite** [comment]
> > Another interesting metric could be to measure the duration that a session has been checked out of the pool.
> 
> Could you please point out the code from where I can fetch this number.
> 

It's currently not being maintained by the session pool, but we could easily add it. This method registers the session as busy by also capturing the stacktrace of the caller that is checking out the session:
https://github.com/googleapis/java-spanner/blob/f3ca198f4ba37ed81fa71b4db4866cbfb27c5bd5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L624

We could add an additional property to `PooledSession` called something like `checkedOutTime` of type `Instant`. This property should be set and reset at the same points as where `leakedException` is set and reset.

**Comment by olavloite** [comment]
> I was thinking to add a counter to measure the count of pool (resource) exhausted or no session available in the pool, to indicate session leaks. WDYT? If this is not the right place, It would be nice if you can point me to the code to get the session leak data.
> 
> https://github.com/googleapis/java-spanner/blob/f3ca198f4ba37ed81fa71b4db4866cbfb27c5bd5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L1430-L1440

I think that counting the number of times a session was not available in the pool (but could be created, i.e. there was no session pool exhaustion) is not something that we need to measure separately, assuming that we already measure `maxSessionsInUse` and `numSessionsInUse`. Those values should give the user a good overview of the number of sessions that is actually needed, and whether it is steadily increasing over time or whether it is relatively constant.

Counting the number of times that a session could not be checked out of the pool because of pool exhaustion could add some value for the user. In such a situation, the user will observer a value for `numSessionsInUse` that is equal to (or almost equal to) `maxSessions` all the time. While that is an indication that something is not well, it could also be that the application and the session pool are operating at their max, but without actually being exhausted. There are two places where you should read this value (or add a counter to measure this value):
1. The place that you had already identified: https://github.com/googleapis/java-spanner/blob/f3ca198f4ba37ed81fa71b4db4866cbfb27c5bd5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L1430-L1440
1. The `Waiter.take()` method: https://github.com/googleapis/java-spanner/blob/f3ca198f4ba37ed81fa71b4db4866cbfb27c5bd5/google-cloud-spanner/src/main/java/com/google/cloud/spanner/SessionPool.java#L867

Some background information on the above:
Bullet 1 will only be executed if `SessionPoolOptions.setFailIfPoolExhausted()` has been set. That is not the default, and most users will not have set it. The other (default) option is to block and wait. This is where bullet 2 comes in.

The session pool will by default block and wait if no session can be returned from the pool. This blocking wait is implemented in the `take()` method of the inner class `Waiter`. This method will block indefinitely if all the sessions in the pool have been leaked. It will however wake up every 30 to 240 seconds to log a `DEADLINE_EXCEEDED` warning. These 'timeouts' is the other metric that you should measure.

**Comment by mayurkale22** [comment]
> Counting the number of times that a session could not be checked out of the pool because of pool exhaustion could add some value for the user.

SGTM. Looks like this is possible to measure via `getNumWaiterTimeouts()` method and this value is always increasing so makes sense to measure it as Counter (or Cumulative) instead of Gauge.

Just for my understanding: As a user, when I see 'timeouts' number growing what are the remedies would you suggest (apart from increasing the session pool size)?

**Comment by olavloite** [comment]
> Just for my understanding: As a user, when I see 'timeouts' number growing what are the remedies would you suggest (apart from increasing the session pool size)?

1. Check your application log for `LeakedSessionException`s that occur when you close your `Spanner` instance. (Closing a `Spanner` instance will close the session pool, and closing the session pool will trigger these `LeakedSessionException`s for all sessions that have not been checked back in to the session pool before closing the pool.)
1. If you have `LeakedSessionException`s: Investigate the stacktrace of these and fix the code that is checking out the session, but not checking them back in, by for example not closing all `ResultSet`s or by not closing a read-only transaction.
1. If you do not have `LeakedSessionException`s: Increase `SessionPool.maxSessions`.

**Comment by mayurkale22** [comment]
I see, thanks for clearing my doubt.  I will include 'timeouts' metric in next PR.

**Comment by skuruppu** [comment]
> @skuruppu What do you think about [#53 (comment)](https://github.com/googleapis/java-spanner/issues/53#issuecomment-582027067)?

I agree that we should add these metrics. But given that the first iteration of this work is meant to  help with detecting sessions leaks, I would prioritize these after the first iteration is done.

**Comment by mayurkale22** [comment]
@olavloite In the next installment, I am thinking to include below set of metrics. Would like to know your thoughts.

1. `cloud.google.com/java/spanner/acquired_sessions`
The total count of sessions acquired by user or pool manager (or maintainer). This metric labeled with database name, instance_id, library_version and acquired_by.

2. `cloud.google.com/java/spanner/released_sessions`
The total count of sessions released explicitly by the user or pool manager (or maintainer). This metric labeled with database name, instance_id, library_version and released_by. 

These metrics might help users to understand the session leaks by following ways: 
- In ideal condition, number of acquired sessions should be equal to (or almost equal to) released sessions count. If not, this is a clear indication of something is not well.
- The number of sessions released by the pool manager should be as low as possible (based on my limited knowledge, pool manager is responsible for tracking and closing the idle sessions over a window of 10 minutes).

**Comment by olavloite** [comment]
Having the total number of acquired and released sessions could be interesting. If the difference between the two is steadily increasing, it is certainly an indication that there is a session leak. The metric is also an indication of the load on the system, so if you were to present it as a timeline, a user would be able to recognize peak and low load moments.

I'm not sure we should count the number of times the pool manager acquires and releases sessions, as I don't think the users would be able to understand what it would mean. The metrics would also not be an indication of any problems. The pool manager does not do anything with leaked sessions, as the pool manager thinks that a leaked session is still in use by the user application. The pool manager is responsible for:
* Pinging sessions that haven't been used for X time, where the default for X is 30 minutes.
* Closing idle sessions. A session is considered idle if it has not been used during the last 10 minutes. The maintainer will only close as many sessions that is necessary to reach the value `minSessions + maxIdleSessions`. E.g. assume that the user has specified `minSessions=100` and `maxIdleSessions=100`. The current total number of sessions in the pool is 300 and the maintainer determines that 200 of those sessions have been idle for the last 10 minutes. It will then close 100 of those sessions, as it wants to keep at least 200 sessions (`maxIdle + minSessions`).

So I don't think you can use any metrics from the maintainer to determine potential session leaks.

Metrics from the maintainer could be interesting to help the user identify other optimizations, although I don't think these are the most important ones:
* The number of sessions that needed to be pinged: If you have a high number of sessions that need to be pinged, it is an indication that the number of sessions in your pool is higher than is necessary. A session is only pinged if it hasn't been used for 30 minutes or more. Ideally, you should have a buffer of sessions that get pinged, as it is generally cheaper to have a little reserve of sessions in the pool than to create sessions on-demand.
* The number of sessions closed by the maintainer: If the maintainer is closing sessions, it is an indication that the load on the system is not constant. If this behavior can be related to logical fluctuations in application load, then it is not a problem (e.g. the maintainer starts closing sessions at the end of a business day for an application that is normally only used during business hours). If it closing sessions on a regular basis during normal application load, it is an indication that the setting for `minSessions` or `maxIdleSessions` probably should be increased. It is better to keep the number of sessions in the pool relatively stable during normal application load, instead of having the pool close and re-create sessions all the time.

**Comment by mayurkale22** [comment]
@skuruppu and @olavloite What do you think about below metrics. Offline reported by the user.

* **Available Sessions in the pool** 
   Mayur: Initially I thought you can calculate this by `max_allowed_sessions ` - `in_use_sessions`
* **ResourceExhaustedExceptions**
   Mayur: Is this same as `get_session_timeouts` metric?
* **Session usage time**

**Comment by skuruppu** [comment]
> * **Available Sessions in the pool**
+1

> * **ResourceExhaustedExceptions**
I didn't think we could get this exception anymore because the backend no longer has limits on the number of sessions that can be created.

> * **Session usage time**
Maybe. Will this be an avg, max?

**Comment by olavloite** [comment]
> 
> * **Available Sessions in the pool**
>   Mayur: Initially I thought you can calculate this by `max_allowed_sessions ` - `in_use_sessions`

+1
This should be calculated as `getNumberOfSessionsInPool() - numSessionsInUse`. The number of sessions in the pool is not necessarily equal to `max_allowed_sessions`.

> * **ResourceExhaustedExceptions**
>   Mayur: Is this same as `get_session_timeouts` metric?

As @skuruppu said; this error is no longer returned by the backend. Previously, the backend had a limit on the number of sessions that could be created. The limit depended on the number of instances in the backend, but the limit has been removed.

**Comment by prateekr** [comment]
To clarify, by ResourceExhaustedException, I'd referring to the fast fail mode that immediately returns an exception if a session is not available and one cannot be created (due to session pool limits) upon request.

**Comment by prateekr** [comment]
>> Session usage time

> Maybe. Will this be an avg, max?

Ah good point; I was hoping for a distribution with including distributions that cover extreme cases (+ 600sec or so).  (eg. Buckets used for gRPC: https://github.com/census-instrumentation/opencensus-java/blob/8b1fd5bbf98b27d0ad27394891e0c64c1171cb2b/contrib/grpc_metrics/src/main/java/io/opencensus/contrib/grpc/metrics/RpcViewConstants.java#L110-L117)

Also, to cover potential scenarios where the Spanner service latencies degrade, what are your thoughts on the following additions:

[Gauge] Sessions being created at the present time
[Gauge] Number of requests in flight (I imagine there is some component that tracks and enforces the 100 rpc per channel limit?)

**Comment by mayurkale22** [comment]
Is it safe to say: number of sessions in pool == `numSessionsInUse + numSessionsBeingPrepared + readSessions.size() + writePreparedSessions.size();`?

If above statement is true, I was thinking to add "**number of sessions in pool**" metric with Type label, this might help users to understand the sessions usage/pattern in the pool. They can break down the data (using labels) as per their need.

![Screen Shot 2020-03-19 at 12 24 47 PM](https://user-images.githubusercontent.com/6525361/77106719-ca8a3c00-69dc-11ea-9513-e8de71f3535a.png)

Also, with this we can drop `in_use_sessions` metric and rely on above metric to provide the same information. This is useful in terms of reducing the metric export cost. WDYT?

**Comment by olavloite** [comment]
> Is it safe to say: number of sessions in pool == `numSessionsInUse + numSessionsBeingPrepared + readSessions.size() + writePreparedSessions.size();`?

Yes

> Also, with this we can drop in_use_sessions metric and rely on above metric to provide the same information. This is useful in terms of reducing the metric export cost. WDYT?

I'm not sure I understand this correctly. Would that mean that the `in_use` metric would disappear from the above dashboard? Or that it would still be there, but it would be calculated from the other metrics? Because I think showing it as a separate metric is valuable in terms of keeping it understandable for a user.

**Comment by mayurkale22** [comment]
Let me try to explain in detail: To support **Available Sessions in the pool** requirement, we have two options.

Option 1:

- Add new metric: `cloud.google.com/java/spanner/num_available_sessions_in_pool` with existing label_keys (`database`, `instance_id`, `library_version`) and use `getNumberOfSessionsInPool() - numSessionsInUse` to calculate the value.

Option 2:
- Remove existing `cloud.google.com/java/spanner/in_use_sessions` metric.
- Add new metric `cloud.google.com/java/spanner/num_sessions_in_pool` with existing label_keys + one extra label to indicate the type/state of sessions. The type (or state) could have one of these names: `in_use_sessions`, `num_session_being_prepared`, `num_read_sessions` and `num_write_prepared_sessions`.
This is how it will look in OpenCensus/Stackdriver (1 Metric with 4 TimeSeries):
Metric: `{name: cloud.google.com/java/spanner/num_sessions_in_pool, desc, unit, etc}`
TimeSeries:  ```[
 {label_values: [database1, instance1, 1.52, in_use_sessions], value: a},
 {label_values: [database1, instance1, 1.52, num_session_being_prepared], value: b},
 {label_values: [database1, instance1, 1.52, num_read_sessions], value: c},
 {label_values: [database1, instance1, 1.52, num_write_prepared_sessions], value: d}
]``` 
- At a high level, users can see the total number of sessions in the pool and if they want, they can break down count by type or state. i.e. combination of `num_session_being_prepared`, `num_read_sessions` and `num_write_prepared_sessions` would give them current available sessions in the pool. 

I am in favor of option 2 mainly due to we consolidate two metrics into one and provide more granular details to users to understand the session pool data. I think the impact of removing existing metric is minimal as we are still in the early stage.

**Comment by olavloite** [comment]
@mayurkale22 Thanks for the detailed explanation, that's clear to me now. Option 2 sounds reasonable to me.

**Comment by Dnefedkin** [comment]
It would be really appreciated if all the OpenCensus metrics that this client library emits are documented in the README.md

**Comment by skuruppu** [comment]
Thanks for the suggestion @Dnefedkin. We can add the metrics to the README.md.

In the meantime, you can take a look at https://medium.com/@mayurkale22/troubleshooting-cloud-spanner-applications-with-opencensus-2cf424c4c590 which lists the metrics and how you might use each metric to debug issues.

**Comment by mayurkale22** [comment]
> It would be really appreciated if all the OpenCensus metrics that this client library emits are documented in the README.md

https://github.com/googleapis/java-spanner/pull/244 is opened to address this.

**Comment by skuruppu** [comment]
@mayurkale22 just want to check if all the work here is done or if there's more work we should do?

**Comment by mayurkale22** [comment]
I think all work has been completed, we can close this issue.

**Comment by skuruppu** [comment]
Perfect, thanks @mayurkale22 for all your hard work.
